version: "3.3"

services:

  spark-master:
    build: ./docker   
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"
    
  spark-worker:
    build: ./docker 
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"

  spark-driver:
    build: ./docker
    image: spark-driver
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network
    volumes:
      - "./:/project"
      
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default